# Generated by Django 3.2.7 on 2021-09-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA_EXTRACT_DATE', models.DateTimeField()),
                ('REPORT_PERIOD', models.DateTimeField()),
                ('ARRIVAL_DEPARTURE', models.CharField(choices=[('Departure', 'Departure'), ('Arrival', 'Arrival')], max_length=20)),
                ('DOMESTIC_INTERNATIONAL', models.CharField(choices=[('International', 'International'), ('Domestic', 'Domestic')], max_length=20)),
                ('PASSENGER_COUNT', models.IntegerField()),
            ],
        ),
    ]
